services:

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8000
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - authentication
    # Aquí puedes agregar los otros servicios base

  # Microservicio de Autenticación
  authentication:
    build: ./services/authentication
    container_name: authentication
    env_file:
      - .env
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mongodb://auth-db:27017/auth_db
    depends_on:
      - auth-db

  # Base de datos para el servicio de autenticación
  auth-db:
    image: mongo:latest
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db

  # --- Plantillas de Microservicios ---
  # TODO: Copiar y modificar "service1" para cada servicio según el tema seleccionado
  
  # Microservicio de Nombre_del_microservicio
  restaurantes-service:
     build: ./services/restaurantes
     container_name: restaurantes-service
     env_file:
      - .env
     ports:
       - "8002:8002"
     environment:
       - DATABASE_URL=postgresql://user:password@service1-db:5432/service1_db
     depends_on:
       - restaurantes-db

  # Base de datos para el servicio1
  restaurantes-db:
     image: postgres:latest
     container_name: restaurantes-db
     environment:
       - POSTGRES_USER=user
       - POSTGRES_PASSWORD=password
       - POSTGRES_DB=service1_db
     ports:
       - "5432:5432"
     volumes:
       - restaurantes_data:/var/lib/postgresql/data

  # Microservicio de Pedidos
  pedidos-service:
    build: ./services/pedidos
    container_name: pedidos-service
    env_file:
      - .env
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://user:password@pedidos-db:5432/pedidos_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - pedidos-db
      - redis

  # Base de datos para Pedidos
  pedidos-db:
    image: postgres:latest
    container_name: pedidos-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pedidos_db
    ports:
      - "5433:5432"
    volumes:
      - pedidos_data:/var/lib/postgresql/data

  # Redis para caché/sesiones/coordination
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  auth_data:
  restaurantes_data:
  pedidos_data:
  repartidores_data:
  redis_data:
